[env]

SERVICE_DB_URL="postgres://app_user:dev_only_pwd@localhost/app_db"
# Scope down tracing, to filter out external lib tracing logs.
RUST_LOG="rust_web_app=debug"

## -- ConfigMap
SERVICE_WEB_FOLDER="web-folder/"